config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  resources :manufacturers, only: [:index, :show, :new, :create, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/manufacturer.rb
class Manufacturer < ApplicationRecord
  validates :name, presence: { message: 'Nome não pode ficar em branco' }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/manufacturers_controller.rb
class ManufacturersController < ApplicationController
  def index
    @manufacturers = Manufacturer.all
  end

  def show
    @manufacturer = Manufacturer.find(params[:id])
  end

  def new
    @manufacturer = Manufacturer.new
  end

  def edit
    @manufacturer = Manufacturer.find(params[:id])
  end

  def create
    @manufacturer = Manufacturer.new(manufacturer_params)
    if @manufacturer.save
      flash[:notice] = 'Fabricante criada com sucesso'
      redirect_to @manufacturer
    else
      # flash.now[:alert] = 'Você deve corrigir os seguintes erros'
      render :new
    end
  end

  def update
    @manufacturer = Manufacturer.find(params[:id])
    @manufacturer.update(manufacturer_params)
    redirect_to @manufacturer
  end

  private

  def manufacturer_params
    params.require(:manufacturer).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1>Rental Cars</h1>
<h3>Bem vindo ao sistema de gestão de locação</h3>

<%= link_to 'Fabricantes', manufacturers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RentalCars</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/manufacturers/edit.html.erb
<h1>Atualizar Fabricante</h1>

<%= form_with model: @manufacturer, local: true do |f| %>
  <%= f.label :name, 'Nome' %>
  <%= f.text_field :name %>
  <%= f.submit 'Enviar' %>
<% end %>

app/views/manufacturers/index.html.erb
<%= link_to 'Registrar novo fabricante', new_manufacturer_path %>

<% @manufacturers.each do |manufacturer| %>
  <%= link_to manufacturer.name, manufacturer %>
<% end %>

app/views/manufacturers/new.html.erb
<h1>Nova Fabricante</h1>

<% if @manufacturer.errors.any? %>
  <p>Você corrigir os seguintes erros para continuar:</p>

  <% @manufacturer.errors.full_messages.each do |message| %>
    <p><%= message %></p>
  <% end %>
<% end %>

<%= form_for @manufacturer do |f| %>
  <%= f.label :name, 'Nome' %>
  <%= f.text_field :name %>
  <%= f.submit 'Enviar' %>
<% end %>

app/views/manufacturers/show.html.erb
<%= flash[:notice] %>

<%= @manufacturer.name %>

<%= link_to 'Editar', edit_manufacturer_path(@manufacturer) %>

<%= link_to 'Voltar', root_path %>